-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Jun 22, 2018 at 08:31 AM
-- Server version: 5.6.38
-- PHP Version: 7.2.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `formulaire`
--

-- --------------------------------------------------------

--
-- Table structure for table `enigme`
--

CREATE TABLE `enigme` (
  `id` int(255) NOT NULL,
  `mot` varchar(50) NOT NULL,
  `theme` varchar(50) NOT NULL,
  `image0` varchar(200) NOT NULL,
  `imgcrop0` varchar(50) NOT NULL,
  `auteur0` varchar(50) NOT NULL,
  `date0` varchar(50) NOT NULL,
  `indice1` varchar(50) NOT NULL,
  `image1` varchar(200) NOT NULL,
  `imgcrop1` varchar(50) NOT NULL,
  `auteur1` varchar(50) NOT NULL,
  `date1` varchar(50) NOT NULL,
  `indice2` varchar(50) NOT NULL,
  `image2` varchar(200) NOT NULL,
  `imgcrop2` varchar(50) NOT NULL,
  `auteur2` varchar(50) NOT NULL,
  `date2` varchar(50) NOT NULL,
  `indice3` varchar(50) NOT NULL,
  `image3` varchar(200) NOT NULL,
  `imgcrop3` varchar(50) NOT NULL,
  `auteur3` varchar(50) NOT NULL,
  `date3` varchar(50) NOT NULL,
  `recompense` varchar(50) NOT NULL,
  `image4` varchar(200) NOT NULL,
  `imgcrop4` varchar(50) NOT NULL,
  `auteur4` varchar(50) NOT NULL,
  `date4` varchar(50) NOT NULL,
  `legende` text NOT NULL,
  `actif` varchar(3) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `enigme`
--

INSERT INTO `enigme` (`id`, `mot`, `theme`, `image0`, `imgcrop0`, `auteur0`, `date0`, `indice1`, `image1`, `imgcrop1`, `auteur1`, `date1`, `indice2`, `image2`, `imgcrop2`, `auteur2`, `date2`, `indice3`, `image3`, `imgcrop3`, `auteur3`, `date3`, `recompense`, `image4`, `imgcrop4`, `auteur4`, `date4`, `legende`, `actif`) VALUES
(3, 'Couvent', 'un lieu de méditation', 'https://upload.wikimedia.org/wikipedia/fr/f/f5/La_tourette-_arq._Le_Corbusier.jpg', 'enigme/0003/image/image0-crop.jpg', 'fusion-of-horizons', '24 octobre 2002', 'Anish KapooR', 'https://upload.wikimedia.org/wikipedia/commons/9/99/Anish_Kapoor_at_the_Deutsche_Guggenheim_-_Berlin.jpg', 'enigme/0003/image/image1-crop.jpg', 'Torsodog', '10 juillet 2009', 'Iannis Xenakis', 'https://upload.wikimedia.org/wikipedia/commons/3/31/Iannis_Xenakis_1975.jpg', 'enigme/0003/image/image2-crop.jpg', 'Cyrus Sixguns', '7 June 2007', 'Le Corbusier', 'https://upload.wikimedia.org/wikipedia/commons/2/23/Le_Corbusier_1933.JPG', 'enigme/0003/image/image3-crop.jpg', 'Inconnu', '1 janvier 1933', 'Le couvent de La Tourette', 'https://upload.wikimedia.org/wikipedia/fr/f/f5/La_tourette-_arq._Le_Corbusier.jpg', 'enigme/0003/image/image4-crop.jpg', 'Alexandre Norman', '2007-09-16', 'Le couvent de La Tourette est une œuvre majeure de l\'architecte Le Corbusier. Les vitrages se veulent l\'adaptation de l\'œuvre Metastasis composée par Iannis Xenakis. L\'artiste plasticien Anish Kapoor fut l\'invité de la dernière biennale d\'art contemporain.', 'on'),
(2, 'SAINT-PAUL', 'un lieu de transit', 'https://upload.wikimedia.org/wikipedia/commons/9/96/GareStPaulLyon.JPG', 'enigme/0002/image/image0-crop.jpg', 'Andrea Caldarelli', 'Inconnue', 'Tunnel', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Lyon_Gorges_de_Loup_II.JPG', 'enigme/0002/image/image1-crop.jpg', 'Smiley.toerist', '21 mars 2009', 'Tram-train', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Tramtrain_in_l%27Arbresle_III.JPG', 'enigme/0002/image/image2-crop.jpg', 'Smiley.toerist', '18 octobre 2012', 'Horloger', 'https://c1.staticflickr.com/3/2853/11139667303_c0cc36843a_b.jpg', 'enigme/0002/image/image3-crop.jpg', 'Serge Barès', '29 novembre 2013', 'la gare Saint-Paul ', 'https://upload.wikimedia.org/wikipedia/commons/9/96/GareStPaulLyon.JPG', 'enigme/0002/image/image4-crop.jpg', 'Gotty', '28 septembre 2006', 'Chaque jour, 5 500 voyageurs passent par la gare Saint-Paul située dans le vieux Lyon où fut tourné le film de Bertrand Tavernier  “L\'horloger de Saint Paul” 1974. Le premier tram-train fut inauguré en septembre 2012.', 'on'),
(0, 'micheline', 'un mode de transport', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Lyon_St_Paul.JPG', 'enigme/0000/image/image0-crop.jpg', 'Oxyman', '29 mars 2009', 'Bugatti', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Bugatti_pr%C3%A9sidentiel%2C_Cit%C3%A9_du_train.jpg/1280px-Bugatti_pr%C3%A9sidentiel%2C_Cit%C3%A9_du_train.jpg', 'enigme/0000/image/image1-crop.jpg', 'Hugh Llewelyn', '29 mars 2009', 'Bibendum', 'https://upload.wikimedia.org/wikipedia/commons/8/88/Michelin_Poster_1898.jpg', 'enigme/0000/image/image2-crop.jpg', 'Ragilnih', '23 novembre 2017 ', 'Locomotive', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/France_Paris_Champs_Elysees_Autorail_Picasso.JPG', 'enigme/0000/image/image3-crop.jpg', 'GIRAUD Patrick', '29 mai 2003', 'Micheline', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Lyon_St_Paul.JPG', 'enigme/0000/image/image4-crop.jpg', 'Smiley.toerist', '21 mars 2009', 'La « Micheline » est un autorail rapide équipé de roues spéciales munies de pneus brevetés appelés  “pneurail”. Elle est construite par la société Michelin dans les années 1935. Bugatti réalisera également de tels véhicules de luxe dès 1932.', 'on'),
(1, 'Wagon-Lit', 'un mode de transport', 'https://c2.staticflickr.com/6/5499/9772695506_c3e1aa39e8_b.jpg', 'enigme/0001/image/image0-crop.jpg', 'patrick janicek', '14 septembre 2013 ', 'L\'Orient Express', 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Gare_Austerlitz_Orient_expres_2.jpg', 'enigme/0001/image/image1-crop.jpg', 'Smiley.toerist', '1 mai 1983', 'Georges Nagelmackers', 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Georges_Nagelmackers_par_Nadar.jpg', 'enigme/0001/image/image2-crop.jpg', 'Nadar', '5 juillet 2011', 'Intercités', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/L%27Intercit%C3%A9s_de_nuit_Paris_-_Austerlitz_Brian%C3%A7on_entre_en_gare_de_Brian%C3%A7on.jpg', 'enigme/0001/image/image3-crop.jpg', 'Damd071', '15 mars 2016', 'LA Compagnie internationale des Wagons-lits', 'https://upload.wikimedia.org/wikipedia/commons/4/4a/CIWL-Logo-bleu.jpg', 'enigme/0001/image/image4-crop.jpg', 'Tamorlan', '18 février 2014', 'La Compagnie internationale des Wagons-lits est une entreprise française d\'origine belge, fondée par Georges Nagelmackers en 1872. Intercités de nuit désigne, depuis 2012, le service de trains de nuit réguliers, proposé par la SNCF, réalisé avec des voitures Corail.', 'on'),
(4, 'Funiculaire', 'un mode de transport', 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Funiculaire_de_Lyon_%28France%29.JPG', 'enigme/0004/image/image0-crop.jpg', 'Tusco', '5 juillet 2013', 'Ficelle', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Bindfaden.jpg', 'enigme/0004/image/image1-crop.jpg', 'Daniel Schwen', '26 août 2005', 'Crémaillère', 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Cr%C3%A9maill%C3%A8re_-_Panoramique_des_D%C3%B4mes.jpg', 'enigme/0004/image/image2-crop.jpg', 'Matthieu Riegler', '14 août 2012', 'Coline', 'https://c2.staticflickr.com/4/3317/3187917446_cfb9c23ff7_b.jpg', 'enigme/0004/image/image3-crop.jpg', 'Mighty Dutchman', '28 décembre 2008', 'Funiculaire de lyon', 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Funiculaire.jpg', 'enigme/0004/image/image4-crop.jpg', 'Magicludovic', '6 mai 2016 ', 'Appelé « Ficelle » par les Lyonnais, le funiculaire sert à parcourir des reliefs pentus. Composé de deux rames et d\'un système de poulies et crémaillère, les wagons s\'auto-tractent par un câble. Leur poids respectif compensant tout ou partie la masse à déplacer du haut vers le bas et inversement. Jadis Lyon possédait 5 funiculaires.', 'on'),
(5, 'Vaporetto', 'un mode de transport', 'https://upload.wikimedia.org/wikipedia/commons/4/44/Vaporetto_Lyon_-02.jpg', 'enigme/0005/image/image0-crop.jpg', 'Tusco', '5 juillet 2013', 'Saône', 'https://upload.wikimedia.org/wikipedia/commons/9/95/Lyon_quaisaone_congres.jpg', 'enigme/0005/image/image1-crop.jpg', 'Inconnu', 'entre 1890 et 1905', 'Confluence', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Confluence_Lyon.jpg', 'enigme/0005/image/image2-crop.jpg', 'Prométhée', '27 septembre 2015', 'Bateau bus', 'https://upload.wikimedia.org/wikipedia/commons/0/07/ItVapporetto_Nuovo.JPG', 'enigme/0005/image/image3-crop.jpg', 'Enri82ve', '1 juin 2006', 'Vaporetto', 'https://c1.staticflickr.com/5/4411/36370007813_9f22d7f689_b.jpg', 'enigme/0005/image/image4-crop.jpg', 'Barry Marsh', '5 septembre 2017 ', 'C\'est en 1881 que le premier Vaporetto fut construit à Nantes et introduit sur la lagune de Venise. À Lyon, c\'est sur la Saône que ce bateau-bus vous emmènera de Saint-Paul à confluence, vous permettant de découvrir la ville sous un autre angle.', 'on'),
(6, 'Aqueduc', 'un monument historique', 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Aqueduc_du_Gier-Chaponost-Plat_de_l%27Air-Conduite_sur_arc.JPG', 'enigme/0006/image/image0-crop.jpg', 'Jmh2o', '23 août 2010', 'L\'Architecture romaine', 'https://upload.wikimedia.org/wikipedia/commons/5/50/Lawrence_Alma-Tadema_05.jpeg', 'enigme/0006/image/image1-crop.jpg', 'Lawrence Alma-Tadema', '1 janvier 1877', 'L\'eau', 'https://upload.wikimedia.org/wikipedia/commons/6/66/Thermes_Romains_Lyon5_fr.JPG', 'enigme/0006/image/image2-crop.jpg', 'Alorange', '15 mars 2008', 'Chaponost', 'https://upload.wikimedia.org/wikipedia/commons/8/86/Chaponost_l%27%C3%A9glise.JPG', 'enigme/0006/image/image3-crop.jpg', 'Frachet', '1 novembre 2009', 'l\'aqueduc du Gier', 'https://upload.wikimedia.org/wikipedia/commons/7/70/Aqueduc_du_Gier_-_Chaponost_-_Arches_apr%C3%A8s_r%C3%A9novation_2009-2010.JPG', 'enigme/0006/image/image4-crop.jpg', 'Arnaud Fafournoux', '29 octobre 2010', 'Desservant la ville antique de Lugdunum, l\'aqueduc du Gier pourrait remonter à l\'époque d\'Auguste. C\'est le plus long des 4 aqueducs qui alimentaient la ville en eau. Il est classé monument historique. On retrouve ses traces de Saint-Chamond (42) à Saint-just (69) en passant par Chaponost et Oullins.', 'on'),
(7, 'BASILIQUE', 'un lieu de culte', 'https://c2.staticflickr.com/8/7569/15939822990_c14d3f96f5_b.jpg', 'enigme/0007/image/image0-crop.jpg', ' Dennis Jarvis', '3 juillet 2014', 'montagne mystique', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jules_Michelet.jpg/800px-Jules_Michelet.jpg', 'enigme/0007/image/image1-crop.jpg', 'Thomas Couture', 'Inconnue', 'pierre bossan', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Pierre_Bossan.JPG/800px-Pierre_Bossan.JPG', 'enigme/0007/image/image2-crop.jpg', 'Inconnu', 'inconnue', 'vierge marie', 'https://c2.staticflickr.com/8/7322/14166938371_3f1accd36d_b.jpg', 'enigme/0007/image/image3-crop.jpg', 'Luc Legay', '26 avril 2014 ', 'La BASILIQUE DE FOURVIÈRE', 'https://c2.staticflickr.com/8/7569/15939822990_c14d3f96f5_b.jpg', 'enigme/0007/image/image4-crop.jpg', 'librairie mollat', '30 mai 2015', 'C\'est sur la colline de Fourvière surnomée la « montagne mystique » par Jules Michelet que la basilique Notre-Dame de Fourvière surplombe la ville de Lyon depuis la fin du XIXe siècle. \r\nSon architecture de style néo-byzantin ou romano-byzantin est l\'œuvre de Pierre Bossan. \r\nC\'est à la suite d\'un vœu prononcé en 1642 pour éloigner une épidémie de peste de Lyon, qu\'une statue de Marie fut érigée sur son clocher. ', 'on'),
(8, 'Louise Labé', 'une poétesse du XVIe siècle', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Louise_Lab%C3%A9_page_titre_1556.jpg', 'enigme/0008/image/image0-crop.jpg', 'Pierre Woeiriot', 'Inconnue', 'Femme de lettre', 'https://c2.staticflickr.com/4/3677/12360189544_52bd60f677_b.jpg', 'enigme/0008/image/image1-crop.jpg', ' Étienne Pouvreau', '27 mars 2015 ', 'fille de cordier', 'https://upload.wikimedia.org/wikipedia/commons/9/98/Mendel_I_016_r.jpg', 'enigme/0008/image/image2-crop.jpg', 'Etienne Mahler', '3 décembre 2016', 'École de Lyon (littérature) XVIème siècle', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Maurice_Sc%C3%A8ve.jpg', 'enigme/0008/image/image3-crop.jpg', 'Renaud Camus', '3 juin 2011', 'Louise Labé', 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Louise_Lab%C3%A9_by_Pierre_Woeiriot.jpg', 'enigme/0008/image/image4-crop.jpg', 'Pierre Woeiriot', '1555', 'Appelée \"La Belle Cordière\", la poétesse Louise Labé ne serait pour certains spécialistes du XVIème siècle, qu\'une fiction élaborée par un groupe de poètes autour de Maurice Scève.', 'on'),
(9, 'cathédrale', 'un lieu de culte', 'https://c2.staticflickr.com/6/5536/10481577463_eb4a0e70b1_b.jpg', 'enigme/0009/image/image0-crop.jpg', ' Jean-Stéphane Laurent', '25 octobre 2013 ', 'gothique', 'https://c1.staticflickr.com/5/4353/36251628291_2a27cee939_b.jpg', 'enigme/0009/image/image1-crop.jpg', ' Guilhem Vellut', '4 août 2017 ', 'fête des lumières', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Cath._St_Jean_%283%29.JPG/1280px-Cath._St_Jean_%283%29.JPG', 'enigme/0009/image/image2-crop.jpg', 'Gone de lyon', '7 décembre 2008', 'Horloge astronomique', 'https://c1.staticflickr.com/5/4438/35631299704_ccd707c083_b.jpg', 'enigme/0009/image/image3-crop.jpg', ' Jeannot Kant', '19 juin 2017 ', 'LA cathédrale saint-jean', 'https://c2.staticflickr.com/6/5536/10481577463_eb4a0e70b1_b.jpg', 'enigme/0009/image/image4-crop.jpg', ' Jean-Stéphane Laurent', '25 octobre 2013', 'La primatiale Saint-Jean-Baptiste-et-Saint-Étienne (dite aussi, plus simplement, cathédrale Saint-Jean) est le siège épiscopal de l\'archidiocèse de Lyon. L\'édifice actuel bâtit sous trois archevêques successifs au moment où l\'architecture occidentale bascula du roman au gothique . Près du cœur, on peut découvrir une magnifique horloge astronomique.', 'on'),
(10, 'théâtre', 'un lieu de spectacle', 'https://c1.staticflickr.com/5/4463/37248725630_bcc63b4293_b.jpg', 'enigme/0010/image/image0-crop.jpg', ' Sandrine Néel', '13 août 2016', 'SPECTACLES', 'https://c2.staticflickr.com/4/3213/3002192025_6b52a8c252_o.jpg', 'enigme/0010/image/image1-crop.jpg', ' opethpainter', '1 novembre 2008 ', 'Odéon', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Od%C3%A9on_antique_Lyon-Rue_boutiques.JPG/1280px-Od%C3%A9on_antique_Lyon-Rue_boutiques.JPG', 'enigme/0010/image/image2-crop.jpg', 'Ursus', '8 mars 2016', 'romain', 'https://c2.staticflickr.com/8/7352/9511937344_0ee4507150_b.jpg', 'enigme/0010/image/image3-crop.jpg', ' patrick janicek', '10 août 2013 ', 'théâtre antique', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Theatre_antique_Fourviere.jpg', 'enigme/0010/image/image4-crop.jpg', 'Flayas', '28 octobre 2005', 'Le théâtre antique de Lugdunum est un des principaux monuments romains visibles à Lyon. Il forme avec ses voisins l\'Odéon antique, le pseudo-sanctuaire de Cybèle et le musée gallo-romain un site archéologique d\'exception. \r\nDurant tout l\'été, il accueille le festival des \"Nuits de Fourvière\" qui rassemble plus de 150 000 spectateurs chaque année.', 'on'),
(11, 'Libraire', 'un métier', 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Gabriel_Charavay.jpg', 'enigme/0011/image/image0-crop.jpg', 'Jeanmichelparis', '9 septembre 2011', 'Livres', 'https://c2.staticflickr.com/2/1173/1225274637_85fac883b1_b.jpg', 'enigme/0011/image/image1-crop.jpg', 'non renseigné', 'non renseigné', 'Commerçant', 'https://c1.staticflickr.com/9/8122/8867798514_4c84265c92_b.jpg', 'enigme/0011/image/image2-crop.jpg', 'non renseigné', 'non renseigné', 'Bibliothèque', 'https://c1.staticflickr.com/9/8389/8481050276_93f6892d8b_b.jpg', 'enigme/0011/image/image3-crop.jpg', 'non renseigné', 'non renseigné', 'Gabriel Charavay', 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Gabriel_Charavay.jpg', 'enigme/0011/image/image4-crop.jpg', 'Jeanmichelparis', '9 septembre 2011', 'Fils d\'une famille de bonnetiers le Libraire Gabriel Charavay est un expert en autographes à Lyon entre 1843 et 1848, puis à Paris de 1857 à 1879. Il publia notamment une notice sur Sylvain Maréchal. Ce dernier, pamphlétaire français et passionné par l’égalité sociale, fut un précurseur de la grève générale et de l’anarchisme.', 'on'),
(12, 'ROMANCIER', 'un métier', 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Damasio.jpg', 'enigme/0012/image/image0-crop.jpg', 'Adrien Barbier', '25 avril 2014', 'Plume', 'https://c2.staticflickr.com/6/5504/14217212802_2312f79456_b.jpg', 'enigme/0012/image/image1-crop.jpg', 'non renseigné', 'non renseigné', 'Roman', 'https://c2.staticflickr.com/4/3934/15425838066_d12c5b4410_b.jpg', 'enigme/0012/image/image2-crop.jpg', 'non renseigné', 'non renseigné', 'Science-Fiction', 'https://c2.staticflickr.com/8/7456/9716901804_97474a81a9_b.jpg', 'enigme/0012/image/image3-crop.jpg', 'non renseigné', 'non renseigné', 'Alain Damasio', 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Damasio.jpg', 'enigme/0012/image/image4-crop.jpg', 'Adrien Barbier', '25 avril 2014', 'Né Alain Raymond le 1er août 1969 à Lyon, Alain DAMSIO est un écrivain de science-fiction.\r\nSon premier texte long vendu à plus de 50 000 exemplaires est “La Zone du dehors\", roman d’anticipation qui s’intéresse aux sociétés de contrôle sous le modèle démocratique.', 'on'),
(13, 'COUSSIN', 'une spécialité lyonnaise', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Coussins_de_Lyon.jpg/1280px-Coussins_de_Lyon.jpg', 'enigme/0013/image/image0-crop.jpg', 'Ji-Elle ', '25 février 2016', 'Confiserie', 'https://c1.staticflickr.com/5/4046/4451569428_da80d90e3e_b.jpg', 'enigme/0013/image/image1-crop.jpg', 'Yohann Legrand', '21 mars 2010', 'Échevins', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Portrait_d%27un_échevin_-_Nicolas_de_Largillierre.jpg/800px-Portrait_d%27un_échevin_-_Nicolas_de_Largillierre.jpg', 'enigme/0013/image/image2-crop.jpg', 'Yelkrokoyade', 'inconnu', 'Pâte d\'amande', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Amande.JPG/1280px-Amande.JPG', 'enigme/0013/image/image3-crop.jpg', 'Med Dhifallah', '28 septembre 2008', 'Coussins de Lyon', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Coussins_de_Lyon.jpg/1280px-Coussins_de_Lyon.jpg', 'enigme/0013/image/image4-crop.jpg', 'Ji-Elle ', '25 février 2016', 'En l\'an 1643, lors de la terrible épidémie de peste qui ravage la cité, les échevins lyonnais organisent une procession vers Fourvière pour implorer la Vierge d\'épargner la ville. Ce faisant, ils remettent un cierge de sept livres de cire et un écu d’or présenté sur un coussin de soie. C\'est ce coussin de soierie qui inspirera la création de la confiserie. ', 'on'),
(14, 'PAPILLOTE', 'une spécialité lyonnaise', 'https://c2.staticflickr.com/6/5789/23895165186_95812ea9c4_b.jpg', 'enigme/0014/image/image0-crop.jpg', ' Nicolas Buffler', '22 décembre 2015 ', 'confiserie', 'https://c1.staticflickr.com/3/2117/2492185805_9d0121dc1b_o.jpg', 'enigme/0014/image/image1-crop.jpg', ' Mark Goebel', '27 mai 2007', 'Cacao', 'https://c1.staticflickr.com/5/4171/33632228684_4d53b0de11_b.jpg', 'enigme/0014/image/image2-crop.jpg', 'arlosmedinav77', '8 juin 2016 ', 'Noël', 'https://c2.staticflickr.com/8/7151/6576584431_b86f3c8fec_b.jpg', 'enigme/0014/image/image3-crop.jpg', ' Frédéric BISSON', '25 décembre 2011 ', 'PAPILLOTE', 'https://c2.staticflickr.com/6/5789/23895165186_95812ea9c4_b.jpg', 'enigme/0014/image/image4-crop.jpg', ' Nicolas Buffler', '22 décembre 2015 ', 'La légende veut que les papillotes soient nées à Lyon (dans le quartier des Terreaux) à la fin du XVIIe siècle, quand le jeune commis du Maître chocolatier Papillot eut l\'idée de charmer sa belle en lui envoyant ses petits mots d\'amour enveloppés autour d\'une confiserie.', 'on'),
(15, 'Truffe', 'une spécialité savoyarde', 'https://c1.staticflickr.com/1/815/40781608292_1649bbc175_b.jpg', 'enigme/0015/image/image0-crop.jpg', 'Jean Weber', '15 octobre 2009 ', 'cacao', 'https://c1.staticflickr.com/9/8621/16728865802_93ce601ff8_b.jpg', 'enigme/0015/image/image1-crop.jpg', ' Giulian Frisoni', '22 juillet 2014 ', 'chambéry', 'https://c1.staticflickr.com/9/8673/16349032797_615cc564aa_b.jpg', 'enigme/0015/image/image2-crop.jpg', ' Ashley Van Haeften', 'inconnu', 'Noël', 'https://c1.staticflickr.com/5/4009/4193015633_ee00effb8f_b.jpg', 'enigme/0015/image/image3-crop.jpg', ' Frédéric BISSON', '12 décembre 2009 ', 'les truffes au chocolat', 'https://c1.staticflickr.com/1/815/40781608292_1649bbc175_b.jpg', 'enigme/0015/image/image4-crop.jpg', 'Jean Weber', '15 octobre 2009 ', 'En décembre 1895, Louis Dufour, pâtissier de Chambéry (Savoie) vient à manquer de matière première pour fabriquer ses friandises de fin d\'année. Refusant le déshonneur de s\'approvisionner chez un confrère, il décide de mélanger de la crème fraiche, de la vanille et du cacao en poudre et de plonger le tout dans du chocolat fondu avant de l\'enrober de poudre de chocolat. La truffe au chocolat est née.', 'on'),
(16, 'bocuse', 'un chef cuisinier', 'https://c1.staticflickr.com/1/215/487900252_72fa1a0e3d_o.jpg', 'enigme/0016/image/image0-crop.jpg', ' Alain Elorza', '7 mai 2007 ', 'Meilleur ouvrier de france', 'https://c2.staticflickr.com/6/5678/22564367624_456d044dc2_b.jpg', 'enigme/0016/image/image1-crop.jpg', ' Yann Caradec', '21 novembre 2015 ', 'L\'auberge', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Int%C3%A9rieur_de_l%27auberge_de_Paul_Bocuse.jpg/1920px-Int%C3%A9rieur_de_l%27auberge_de_Paul_Bocuse.jpg', 'enigme/0016/image/image2-crop.jpg', 'Éric Messel ', '10 avril 2017', 'Poularde aux morilles', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Paul_Bocuse_044.JPG/1280px-Paul_Bocuse_044.JPG', 'enigme/0016/image/image3-crop.jpg', 'Arnaud 25 ', '25 octobre 2013', 'Monsieur paul', 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Paul_Bocuse_2007_-2.jpg', 'enigme/0016/image/image4-crop.jpg', 'Alain Elorza', '7 mai 2007', 'Trois étoiles au Guide Michelin pendant 53 années (de 1965 à 2018), Paul Bocuse compte parmi les plus célèbres cuisiniers du monde et fut un précurseur de la nouvelle cuisine, un maître de la cuisine traditionnelle et de la gastronomie française.', 'on'),
(17, 'pantographe', 'un objet du train', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Pantograf_2.jpg', 'enigme/0017/image/image0-crop.jpg', 'Sheep221', '31 mars 2006', 'caténaire', 'https://c2.staticflickr.com/6/5332/7417425976_65484282d6_b.jpg', 'enigme/0017/image/image1-crop.jpg', 'JPC24M', '13 mai 2012 ', 'locomotive électrique', 'https://c2.staticflickr.com/6/5341/9772761856_36475bf049_b.jpg', 'enigme/0017/image/image2-crop.jpg', 'Patrick Janicek', '14 septembre 2013 ', 'Losange', 'https://c2.staticflickr.com/8/7749/17603762543_7028bfa130_b.jpg', 'enigme/0017/image/image3-crop.jpg', 'Étienne Pouvreau', '19 mai 2015 ', 'pantographe', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Pantograaf_lichtrail.jpg', 'enigme/0017/image/image4-crop.jpg', 'inconnu', '6 mars 2005', 'Le pantographe est le dispositif articulé qui permet à une locomotive électrique ou à un tramway ou à d\'autres systèmes automoteurs électriques de capter le courant par frottement sur une caténaire.', 'on'),
(18, 'l\'arbresle', 'une commune', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Gare_de_L%27Arbresle.JPG/1280px-Gare_de_L%27Arbresle.JPG', 'enigme/0018/image/image0-crop.jpg', 'Camster ', '8 juin 2014', 'son blason', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Blason_ville_fr_L%27Arbresle_%28Rh%C3%B4ne%29.svg/600px-Blason_ville_fr_L%27Arbresle_%28Rh%C3%B4ne%29.svg.png', 'enigme/0018/image/image1-crop.jpg', 'bvs-aca', '18 août 2008', 'Son clocher', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/L%27Arbresle%2C_%C3%A9glise_Nativit%C3%A9de_St_Jean_Baptiste.jpg/399px-L%27Arbresle%2C_%C3%A9glise_Nativit%C3%A9de_St_Jean_Baptiste.jpg', 'enigme/0018/image/image2-crop.jpg', 'Dominique Robert', '19 September 2012', 'la brévenne', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/L%27Arbresle_-_La_Br%C3%A9venne.jpg/1280px-L%27Arbresle_-_La_Br%C3%A9venne.jpg', 'enigme/0018/image/image3-crop.jpg', 'Joannès Drevet', 'inconnue', 'l\'arbresle', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Arbr_2.JPG/1280px-Arbr_2.JPG', 'enigme/0018/image/image4-crop.jpg', 'Julien Bertrand', '11 janvier 2007', 'Comme l\'attestent les armes et outils en silex trouvées au Muzard, l\'homme occupe le site de L\'Arbresle dès le néolithique. Au Moyen-Âge, la ville constitue une halte sur le \"Grand chemin Français\", l\'itinéraire est prisé car il est le plus court pour rejoindre la capitale Paris. Il deviendra le \"Grand chemin de Paris à Lyon\", puis la \"Route Royale\". On la connait aujourd\'hui sous le nom de la Route Nationale 7.', 'on'),
(19, 'troll', 'un personnage relou', 'https://c2.staticflickr.com/8/7134/7578316830_c9a817f081_b.jpg', 'enigme/0019/image/image0-crop.jpg', 'Jan Hammershaug', '15 juillet 2012 ', 'folklore scandinave', 'https://upload.wikimedia.org/wikipedia/commons/1/12/Trollschild.jpg', 'enigme/0019/image/image1-crop.jpg', 'Sebastian.Dietrich ', '30 août 2007', 'internet', 'https://c1.staticflickr.com/3/2878/9561063863_4d51030596_b.jpg', 'enigme/0019/image/image2-crop.jpg', 'Illustrator LdreiT', '21 août 2013 ', 'discussion', 'https://c2.staticflickr.com/2/1001/634224242_1d827058c5_o.jpg', 'enigme/0019/image/image3-crop.jpg', ' Bill Wren', '26 juin 2007 ', 'troll', 'https://c2.staticflickr.com/6/5060/5501482868_1264028a9e_b.jpg', 'enigme/0019/image/image4-crop.jpg', ' Cami Valderrama', '5 mars 2011 ', 'Inspiré du floklore scandinave, on peut se retrouver clic à clic avec un troll sur le net. On les trouve sur les forums ou les réseaux sociaux. Ils se distinguent par leur capacité à créer artificiellement une controverse qui focalise l\'attention sur cette dernière aux dépens des échanges et de l\'équilibre de la discussion.', 'on'),
(20, 'blogueuse', 'un métier', 'https://c2.staticflickr.com/8/7248/7419512924_00f8169cd8_b.jpg', 'enigme/0020/image/image0-crop.jpg', 'inconnu', '3 mars 2012 ', 'Experte', 'https://c2.staticflickr.com/8/7013/6569944913_9da2d76eb9_b.jpg', 'enigme/0020/image/image1-crop.jpg', 'Yohann Legrand', '11 décembre 2011 ', 'passionnée', 'https://c2.staticflickr.com/4/3427/3244186572_9d1c143c83_b.jpg', 'enigme/0020/image/image2-crop.jpg', ' Lauri Rantala', '23 janvier 2009', 'internet', 'https://d30y9cdsu7xlg0.cloudfront.net/png/326129-200.png', 'enigme/0020/image/image3-crop.jpg', 'priyanka', 'inconnue', 'blogueuse', 'https://c2.staticflickr.com/8/7248/7419512924_00f8169cd8_b.jpg', 'enigme/0020/image/image4-crop.jpg', 'inconnu', '3 mars 2012 ', 'Auteur d’un blogue. Personne utilisant Internet comme un moyen de communication pour s’exprimer et diffuser de l’information sur différents sujets pour lesquels elle a une expertise ou une passion. Utilisant les mots, la photo, les vidéos, la blogueuse remixe régulièrement les contenus de différentes sources provenant des médias traditionnels, des communautés en ligne, d’autres blogues et de sites à contenus.\r\n', 'on'),
(21, 'Rabelais', 'un humaniste célèbre', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Francois_Rabelais_-_Portrait.jpg/800px-Francois_Rabelais_-_Portrait.jpg', 'enigme/0021/image/image0-crop.jpg', 'inconnu', 'inconnue', 'Penseur de la renaissance', 'https://upload.wikimedia.org/wikipedia/commons/3/3a/1543%2C_Andreas_Vesalius%27_Fabrica%2C_Base_Of_The_Brain.jpg', 'enigme/0021/image/image1-crop.jpg', 'inconnu', 'inconnue', 'Érudit', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Da_Vinci_Vitruve_Luc_Viatour.jpg/800px-Da_Vinci_Vitruve_Luc_Viatour.jpg', 'enigme/0021/image/image2-crop.jpg', 'inconnu', 'inconnue', 'Protagoras', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Salvator_Rosa_-_D%C3%A9mocrite_et_Protagoras.jpg/800px-Salvator_Rosa_-_D%C3%A9mocrite_et_Protagoras.jpg', 'enigme/0021/image/image3-crop.jpg', 'inconnu', 'inconnue', 'françois Rabelais', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Francois_Rabelais_-_Portrait.jpg/800px-Francois_Rabelais_-_Portrait.jpg', 'enigme/0021/image/image4-crop.jpg', 'inconnu', 'inconnue', 'Médecin à l\'hôtel-Dieu de Lyon cet humaniste et écrivain publia à Lyon : Pantagruel et Gargantua', 'on'),
(22, 'exploratrice', 'un métier', 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Jeanne_Barret.jpg', 'enigme/0022/image/image0-crop.jpg', 'inconnu', 'inconnue', 'Voyageuse', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Recherche_and_Esp%C3%A9rance-Fran%C3%A7ois_Roux_mg_0574.jpg/1920px-Recherche_and_Esp%C3%A9rance-Fran%C3%A7ois_Roux_mg_0574.jpg', 'enigme/0022/image/image1-crop.jpg', 'inconnu', 'inconnue', 'curieuse', 'https://c2.staticflickr.com/4/3417/5804110695_a3b8aa1841_b.jpg', 'enigme/0022/image/image2-crop.jpg', 'Peter Hellberg', '2 juin 2011 ', 'courageuse', 'https://c1.staticflickr.com/1/1/128391936_44e3cd651d_b.jpg', 'enigme/0022/image/image3-crop.jpg', ' Tommy Wong', '14 avril 2006 ', 'Jeanne Barret', 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Jeanne_Barret.jpg', 'enigme/0022/image/image4-crop.jpg', 'inconnu', 'inconnue', 'Exploratrice et botaniste du XVIIIème siècle, Jeanne Barret est notamment connue pour être la première femme à avoir fait le tour du monde sur l\'expédition de Bougainville. Déguisée en homme, elle est engagée sous le nom de Jean Baret comme valet et assistant du naturaliste Philibert Commerson. Plus tard elle l\'aidera à consigner et répertorier les végétaux et à réorganiser les jardins de Lyon. ', 'on'),
(23, 'aubrac', 'une héroïne', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Lucie_aubrac.jpg/800px-Lucie_aubrac.jpg', 'enigme/0023/image/image0-crop.jpg', 'Paulgypteau', '1 mai 2003', 'résistante', 'https://c1.staticflickr.com/1/883/42071851044_e314fa044e_b.jpg', 'enigme/0023/image/image1-crop.jpg', ' Carl T. Bergstrom', '13 juin 2018 ', 'Seconde Guerre mondiale', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Into_the_Jaws_of_Death_23-0455M_edit.jpg/1280px-Into_the_Jaws_of_Death_23-0455M_edit.jpg', 'enigme/0023/image/image2-crop.jpg', 'Robert F. Sargent,', 'le 6 juin 1944', 'avenue berthelot', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Centre_Berthelot_Lyon7_fr.JPG/1280px-Centre_Berthelot_Lyon7_fr.JPG', 'enigme/0023/image/image3-crop.jpg', 'Alorange', '23 mars 2008', 'lucie aubrac', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Lucie_aubrac.jpg/800px-Lucie_aubrac.jpg', 'enigme/0023/image/image4-crop.jpg', 'Paulgypteau', '1 mai 2003', 'Résistante française pendant la Seconde Guerre mondiale, Lucie Aubrac organise en août 1940 l\'évasion de son mari, alors prisonnier de guerre à Sarrebourg. Le couple se réfugie à Lyon mais son mari est de nouveau arrêté cette fois-ci par la Gestapo. Avec d\'autres compagnons, elle organise et participe en septembre 43 à l\'extraction de 14 résistants dont Raymond en attaquant le fourgon allemand sur l\'avenue Berthelot.', 'on'),
(24, 'abbé pierre', 'un héros', 'https://upload.wikimedia.org/wikipedia/commons/6/65/ABBE_PIERRE-1999Without.jpg', 'enigme/0024/image/image0-crop.jpg', 'Studio Harcourt ', '7 août 2010', 'Hiver 54', 'https://c1.staticflickr.com/5/4085/5071112318_51b0a723ab_b.jpg', 'enigme/0024/image/image1-crop.jpg', 'phalenebdlv', 'hiver 54', 'Henri Grouès', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Abb%C3%A9_Pierre_%281955%29.jpg/800px-Abb%C3%A9_Pierre_%281955%29.jpg', 'enigme/0024/image/image2-crop.jpg', 'Wim van Rossem', '7 août 1955', 'mouvement Emmaüs', 'https://c1.staticflickr.com/5/4371/36763175530_fa4708f178_b.jpg', 'enigme/0024/image/image3-crop.jpg', 'Filippo Tarchiani', 'vers 1625', 'L\'abbé pierre', 'https://upload.wikimedia.org/wikipedia/commons/6/65/ABBE_PIERRE-1999Without.jpg', 'enigme/0024/image/image4-crop.jpg', 'Studio Harcourt ', '7 août 2010', 'Henri Grouès, dit l’abbé Pierre est le fondateur du mouvement Emmaüs : organisation non-confessionnelle de lutte contre l\'exclusion. Durant l\'hiver de 1954, il lance un appel sur les ondes qui rapportera 500 millions de francs en dons, dont 2 millions par Charlie Chaplin qui dira à cette occasion : “Je ne les donne pas, je les rends. Ils appartiennent au vagabond que j\'ai été et que j\'ai incarné.”', 'on');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `enigme`
--
ALTER TABLE `enigme`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id` (`id`),
  ADD UNIQUE KEY `id_2` (`id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
